### ISSUE TITLE
MySQL specific functions in SQL cause errors on other DBs

### ISSUE THREAD

**Issue by mudrd8mz** [MoodleBeclever/User_statistics#1]
See https://docs.moodle.org/dev/Plugin_contribution_checklist#Cross-DB_compatibility

```
Error reading from database

More information about this error
Debug info: ERROR: function from_unixtime(bigint) does not exist
LINE 1: SELECT FROM_UNIXTIME(date) AS fecha FROM ...
```

![image](https://user-images.githubusercontent.com/85831/115009304-72a65900-9eac-11eb-8ff7-e3563d3b5802.png)

**Comment by MoodleBeclever** [comment]
Hello!

We've commited the fix for this error.
